% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={PAC 2},
  pdfauthor={Raul Perez Prats},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{PAC 2}
\author{Raul Perez Prats}
\date{2025-01-15}

\begin{document}
\maketitle

\hypertarget{ejercicio-1}{%
\subsection{Ejercicio 1}\label{ejercicio-1}}

\hypertarget{a}{%
\subsubsection{A)}\label{a}}

\begin{verbatim}
##   ID         Lake Alkalinity  pH Calcium Chlorophyll Avg.Mercury X..samples
## 1  1    Alligator        5.9 6.1     3.0         0.7        1.23          5
## 2  2        Annie        3.5 5.1     1.9         3.2        1.33          7
## 3  3       Apopka      116.0 9.1    44.1       128.3        0.04          6
## 4  4 Blue Cypress       39.4 6.9    16.4         3.5        0.44         12
## 5  5        Brick        2.5 4.6     2.9         1.8        1.20         12
## 6  6       Bryant       19.6 7.3     4.5        44.1        0.27         14
##    Min  Max X3yrStand age.data
## 1 0.85 1.43      1.53        1
## 2 0.92 1.90      1.33        0
## 3 0.04 0.06      0.04        0
## 4 0.13 0.84      0.44        0
## 5 0.69 1.50      1.33        1
## 6 0.04 0.48      0.25        1
\end{verbatim}

\hypertarget{b}{%
\subsubsection{B)}\label{b}}

\begin{verbatim}
## Porcentaje de lagos con niveles no saludables de mercurio: 41.50943 %
\end{verbatim}

Para saber si este este estimador que indica que el 41,51\% de los lagos
de florida contienen unos niveles de mercurio superiores a los límites
establecidos debemos tener en cuenta que se muestrearon 53 lagos en el
estudio sobre un total de 7800 en florida acorde a los
\href{https://bcs.whfreeman.com/WebPub/Statistics/shared_resources/EESEE/MercuryinFloridasBass/index.html}{autores}.
Esto implica que tan solo se han usado un 0,68\% de los lagos de florida
para realizar el estudio. Además de la cantidad de lagos muestreados, es
importante conocer la distribución de estos lagos y ésta debería de ser
lo más equitativa posible a lo largo del territorio de Florida para
maximizar la representación de la muestra. En la figura 1 podemos ver
que el mayor esfuerzo de muestreo se concentra en la zona central de
Florida, mientras las zonas norte, este y sur del estado a penas recojen
información de ningún lago.

Los autores mencionan que han usado su criterio para escojer los 53
lagos más representativos de estos 7800 lagos totales. Aún así teniendo
en cuenta que tan solo se ha muestreado el 0,68\% de los lagos creo que
estos 53 lagos no son totalmente representativos del total, ya que el
criterio de los investigadores puede pasar por alto datos relevantes en
los 7747 lagos restantes. Además la distribución del muestreo de estos
lagos no es equitativa, quedando así regiones considerablememte grandes
completamente sin muestras.

Por todos estos motivos creo que la estimación de los lagos con niveles
no saludables de mercurio no es representativa para todos los lagos del
estado de Florida.

\begin{figure}
\centering
\includegraphics[width=5.20833in,height=\textheight]{https://bcs.whfreeman.com/WebPub/Statistics/shared_resources/EESEE/MercuryinFloridasBass/images/bassmap.gif}
\caption{Figura 1: Imagen de dónde se realizaron los muestreos en
florida}
\end{figure}

\hypertarget{c}{%
\subsubsection{C)}\label{c}}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-3-1.pdf}

En todos los diagramas 2 a 2 de las variables vs Avg.Mercury observamos
que la relación no es lineal a simple vista, incluso, algunos gráficos
como Alkalinity vs Avg.Mercury, Calcium vs Avg.Mercury y Chlorophyll vs
Avg.Mercury sugieren un modelo que a simple vista encaja mejor con una
exponencial negativa. Esto sucede porque cuanto mayores son las
concentraciones de calcio, clorofila y alcalinidad, la concentración de
mercurio promedio disminuye.

\includegraphics{project_2_files/figure-latex/unnamed-chunk-4-1.pdf}

Aquí podemos observar el ajuste de una recta a la relación Alcalinidad
vs Mercurio promedio. Tal y como se ha mencionado antes, parece que los
modelos exponenciales negativos tendrían un mejor ajuste en este tipo de
datos.

\hypertarget{d}{%
\subsubsection{D)}\label{d}}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-6-1.pdf}

Tras aplicar la transformación de la función transformTukey() podemos
afirmar que a simple vista, todos las variables han mejorado
considerablemente su relación lineal negativa con la variable objetivo
Avg.Mercury. Ahora los gráficos ya no siguen un modelo de una
exponencial negativa como se podía intuir en los gráficos anteriores.
Aunque, tras la transformación se sigue manteniendo la relación
inversamente proporcional entre las variables y el mercurio promedio, lo
que ahora se aprecia una relación más lineal.

\hypertarget{e}{%
\subsubsection{E)}\label{e}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rcompanion)}

\CommentTok{\# Transformar las variables químicas (X1, X2, X3, X4) y las de mercurio (Y1, Y2, Y3)}
\NormalTok{variables\_transformadas }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{X1 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Alkalinity, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{X2 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{pH, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{X3 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Calcium, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{X4 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Chlorophyll, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{Y1 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Min, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{Y2 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Avg.Mercury, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{Y3 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Max, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcular la matriz de centrado H}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(variables\_transformadas)  }\CommentTok{\# Número de observaciones}
\NormalTok{H }\OtherTok{\textless{}{-}} \FunctionTok{diag}\NormalTok{(n) }\SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ n) }\SpecialCharTok{*} \FunctionTok{matrix}\NormalTok{(}\DecValTok{1}\NormalTok{, n, n)  }\CommentTok{\# Matriz de centrado}

\CommentTok{\# Centrar las variables manualmente (restar la media de cada columna)}
\NormalTok{variables\_centradas }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(variables\_transformadas, }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Calcular la matriz de varianzas{-}covarianzas manualmente}
\NormalTok{var\_cov\_manual }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{*} \FunctionTok{t}\NormalTok{(variables\_centradas) }\SpecialCharTok{\%*\%}\NormalTok{ variables\_centradas}

\CommentTok{\# Comparar con la función cov()}
\NormalTok{var\_cov\_func }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(variables\_transformadas)}

\CommentTok{\# Verificar si los resultados coinciden}
\FunctionTok{all.equal}\NormalTok{(var\_cov\_manual, var\_cov\_func)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

La matriz de covarianzas calculada da el mismo resultado que el calculo
con la funcion cov()

\hypertarget{f}{%
\subsubsection{F)}\label{f}}

\begin{verbatim}
## Media de U:  3.278413
\end{verbatim}

\begin{verbatim}
## Media de V:  0.7367344
\end{verbatim}

\begin{verbatim}
## Varianza de U:  1.144028
\end{verbatim}

\begin{verbatim}
## Varianza de V:  0.05703552
\end{verbatim}

\begin{verbatim}
## Correlación entre U y V:  -0.635784
\end{verbatim}

Como hemos visto en apartados anteriores la alta correlación negativa de
-0.64 concuerda con los gráficos anteriores, donde se observa que con el
aumento de la Alcalinidad, el pH, el calcio y la clorofila la
concentración de mercurio tiende a disminuir.

Este hecho no implica una causalidad directa. Hacen falta análisis más
profundos para determinar que los niveles altos de estas variables son
la causa de disminución de concentración de mercurio.

\hypertarget{g}{%
\subsubsection{G)}\label{g}}

\begin{verbatim}
## Warning: package 'tidyr' was built under R version 4.3.3
\end{verbatim}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-10-1.pdf}

Como hemos mencionado anteriormente, los niveles altos de pH, es decir,
los lagos alcalinos muestran menores concentraciones de mercurio. Este
suceso también se puede observar en el boxplot comparativo en el que los
lagos alcalinos muestran una distribución de valores más bajos tanto
para Y1, Y2 y Y3. Esto se puede apreciar de forma muy clara y evidente
en el gráfico donde los valores de dentro de las cajas (el grueso de las
distribuciones) nunca llega a solaparse en ninguna de las 3 variables.
Por lo tanto, en lagos alcalinos, las concentraciones mínimas, medias y
máximas de mercurio son más bajas que en los lagos de pH ácido.

\hypertarget{h}{%
\subsubsection{H)}\label{h}}

Gráficos de Normalidad Univariante

\includegraphics{project_2_files/figure-latex/unnamed-chunk-11-1.pdf}

La comparación de los qqplots de los grupos ácidos vs alcalinos sugiere
que los datos en el grupo Ácidos tiene un mejor ajuste a una
distribución normal, ya que en el grupo Alcalinos hay un mayor número de
muestras en las colas que se separan de la linea. Este desajuste en el
grupo Alcalino se podría corregir mediante una eliminación de los
outliers, ya que son muy pocos los puntos que en las colas no se ajustan
a la línea del gráfico qqplot.

Test de Normalidad Univariante

\begin{verbatim}
## 
## Resultados para Y1_Ácido :
## 
##  Shapiro-Wilk normality test
## 
## data:  variables_transformadas_sin_ph_7[[var]][variables_transformadas_sin_ph_7$pH_grupo == "Ácido"]
## W = 0.95831, p-value = 0.263
## 
## 
## Resultados para Y1_Alcalino :
## 
##  Shapiro-Wilk normality test
## 
## data:  variables_transformadas_sin_ph_7[[var]][variables_transformadas_sin_ph_7$pH_grupo == "Alcalino"]
## W = 0.85467, p-value = 0.008
## 
## 
## Resultados para Y2_Ácido :
## 
##  Shapiro-Wilk normality test
## 
## data:  variables_transformadas_sin_ph_7[[var]][variables_transformadas_sin_ph_7$pH_grupo == "Ácido"]
## W = 0.98177, p-value = 0.8599
## 
## 
## Resultados para Y2_Alcalino :
## 
##  Shapiro-Wilk normality test
## 
## data:  variables_transformadas_sin_ph_7[[var]][variables_transformadas_sin_ph_7$pH_grupo == "Alcalino"]
## W = 0.93352, p-value = 0.201
## 
## 
## Resultados para Y3_Ácido :
## 
##  Shapiro-Wilk normality test
## 
## data:  variables_transformadas_sin_ph_7[[var]][variables_transformadas_sin_ph_7$pH_grupo == "Ácido"]
## W = 0.97488, p-value = 0.6612
## 
## 
## Resultados para Y3_Alcalino :
## 
##  Shapiro-Wilk normality test
## 
## data:  variables_transformadas_sin_ph_7[[var]][variables_transformadas_sin_ph_7$pH_grupo == "Alcalino"]
## W = 0.94617, p-value = 0.3395
\end{verbatim}

Las observaciones de los qqplots concuerdan con el test de Shapiro-Wilk,
ya que todos los pvalores del grupo Ácido son mayores a 0.05, por lo
tanto no se rechaza la hipótesis nula en este grupo y las muestras
siguen una distribución normal para las 3 variables (Concentración
mínima, Promedio y máxima de mercurio). Por otro lado, en el grupo
alcalino, Y1 (concentración mínima) no se ajusta a una distribución
normal debido a que pvalue = 0.008 \textless{} 0.05. Mientras que Y2 e
Y3 si que se ajustan a una distribución normal. Por lo tanto, teniendo
en cuenta las 3 variables, el grupo Ácido presenta un mejor ajuste a una
distribución normal en las 3 variables.

Asimetría y Kurtosis Multivariante

\begin{verbatim}
## $multivariateNormality
##            Test        HZ   p value MVN
## 1 Henze-Zirkler 0.7183026 0.2197776 YES
## 
## $univariateNormality
##               Test  Variable Statistic   p value Normality
## 1 Anderson-Darling    Y1        0.5100    0.1826    YES   
## 2 Anderson-Darling    Y2        0.1598    0.9431    YES   
## 3 Anderson-Darling    Y3        0.2396    0.7577    YES   
## 
## $Descriptives
##     n      Mean   Std.Dev    Median       Min       Max      25th      75th
## Y1 31 0.7176302 0.1356066 0.7037340 0.4070905 0.9752958 0.6597540 0.8170592
## Y2 31 0.8069077 0.1960582 0.8029468 0.3349654 1.1450634 0.6913652 0.9334280
## Y3 31 1.0377738 0.2701860 1.0284516 0.4609031 1.5067366 0.8662430 1.2208969
##          Skew    Kurtosis
## Y1 -0.2624006 -0.03630929
## Y2 -0.2809076 -0.48601700
## Y3 -0.1298124 -0.68073783
\end{verbatim}

\begin{verbatim}
## $multivariateNormality
##            Test        HZ    p value MVN
## 1 Henze-Zirkler 0.9120179 0.01950433  NO
## 
## $univariateNormality
##               Test  Variable Statistic   p value Normality
## 1 Anderson-Darling    Y1        0.7680    0.0376    NO    
## 2 Anderson-Darling    Y2        0.5039    0.1791    YES   
## 3 Anderson-Darling    Y3        0.3829    0.3617    YES   
## 
## $Descriptives
##     n      Mean   Std.Dev    Median       Min       Max      25th      75th
## Y1 19 0.5165202 0.1422525 0.4855934 0.3807308 0.9317258 0.3939107 0.5770800
## Y2 19 0.5292820 0.2104685 0.5369054 0.2167597 1.0463128 0.4369169 0.5990354
## Y3 19 0.6493894 0.2948766 0.6557129 0.1983522 1.2625613 0.4956013 0.7594530
##         Skew   Kurtosis
## Y1 1.2560460  1.3189087
## Y2 0.6030690  0.1135388
## Y3 0.4246391 -0.4100679
\end{verbatim}

Los test Anderson-Darling para el análisis de la normalidad
multivariante tienen un resultado muy parecido al que hemos visto en el
análisis de la normalidad univariante donde en el grupo Ácido las 3
variables se ajustan correctamente a una distribución normal mientras
que en el grupo Alcalino la variable Y1, al igual que en el análisis
univariante, no se ajusta correctamente a una distribución normal.

Calcular las distancias de Mahalanobis

\includegraphics{project_2_files/figure-latex/unnamed-chunk-14-1.pdf}
\includegraphics{project_2_files/figure-latex/unnamed-chunk-14-2.pdf}

La comparación de los gráficos QQ-plot de las distancias de Mahalanobis
respalda lo observado previamente. En el grupo ácido, las distancias de
Mahalanobis se ajustan adecuadamente a la línea teórica, aunque se
observa un único punto en el extremo superior derecho que se aleja
significativamente del ajuste. En contraste, en el grupo alcalino, los
puntos muestran una mayor dispersión en relación con la línea, lo que
indica un ajuste menos preciso a una distribución normal multivariada.
Esto sugiere que los datos en el grupo alcalino podrían desviarse más de
la normalidad multivariante en comparación con el grupo ácido.

\hypertarget{i}{%
\subsubsection{I)}\label{i}}

\begin{verbatim}
## 
##  Box's M-test for Homogeneity of Covariance Matrices
## 
## data:  Y
## Chi-Sq (approx.) = 9.7819, df = 6, p-value = 0.1341
\end{verbatim}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(>F)
## group  1   0.027 0.8701
##       48
\end{verbatim}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(>F)
## group  1  0.0457 0.8316
##       48
\end{verbatim}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(>F)
## group  1  0.0082 0.9281
##       48
\end{verbatim}

El Box's M-test compara la homogeneidad de matrices de covarianzas
multivariantes entre los grupos. En este caso, el test sugiere que no
hay diferencias significativas (0.1341\textgreater0.05) en las matrices
de covarianzas entre los grupos.

Levene's Test evalúa la homogeneidad de las varianzas univariantes de
cada variable individualmente. Los resultados de Levene sugieren que no
hay diferencias significativas (todos los pvalues \textgreater{} 0.05)
en las varianzas entre los grupos para cada variable individual.

\hypertarget{j}{%
\subsubsection{J)}\label{j}}

\begin{verbatim}
## Test stat:  28.31 
## Numerator df:  3 
## Denominator df:  46 
## P-value:  8.105e-05
\end{verbatim}

Dado que el valor p es considerablemente inferior a 0.05
(8.105e-05\textless0.05), rechazamos la hipótesis nula, que establece
que las medias de los dos grupos son iguales. Por lo tanto existe una
diferencia significativa entre las medias de los grupos Ácido y Alcalino
en las variables Y1, Y2 y Y3.

Este resultado concuerda con las observaciones mencionadas en los
graficos de los apartados C y D donde se observa que cuanto mayor es el
pH, menores son las concentraciones de mercurio, por lo tanto las
diferencias significativas entre las medias de Y1, Y2 e Y3 de ambos
grupos confirman las observaciones anteriores.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(perm)}

\CommentTok{\# Crear una función de permutación para la comparación multivariante}
\NormalTok{perm\_test\_multivariante }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(grupo1, grupo2, }\AttributeTok{num\_permutaciones =} \DecValTok{100000}\NormalTok{) \{}
  \CommentTok{\# Calcular la diferencia de medias observada utilizando la norma de la diferencia de medias}
\NormalTok{  diff\_observada }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{sum}\NormalTok{((}\FunctionTok{colMeans}\NormalTok{(grupo1) }\SpecialCharTok{{-}} \FunctionTok{colMeans}\NormalTok{(grupo2))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
  
  \CommentTok{\# Realizar las permutaciones}
\NormalTok{  diferencias\_permutadas }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(num\_permutaciones, \{}
    \CommentTok{\# Permutar las filas de los dos grupos y recalcular la diferencia de medias}
\NormalTok{    datos\_permutados }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(grupo1, grupo2)}
\NormalTok{    indices\_permutados }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(datos\_permutados))}
\NormalTok{    grupo1\_permutado }\OtherTok{\textless{}{-}}\NormalTok{ datos\_permutados[indices\_permutados[}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(grupo1)], ]}
\NormalTok{    grupo2\_permutado }\OtherTok{\textless{}{-}}\NormalTok{ datos\_permutados[indices\_permutados[(}\FunctionTok{nrow}\NormalTok{(grupo1)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(datos\_permutados)], ]}
    \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{sum}\NormalTok{((}\FunctionTok{colMeans}\NormalTok{(grupo1\_permutado) }\SpecialCharTok{{-}} \FunctionTok{colMeans}\NormalTok{(grupo2\_permutado))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{  \})}
  
  \CommentTok{\# Calcular el valor p}
\NormalTok{  p\_value }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(diferencias\_permutadas }\SpecialCharTok{\textgreater{}=}\NormalTok{ diff\_observada)}
  \FunctionTok{return}\NormalTok{(p\_value)}
\NormalTok{\}}

\CommentTok{\# Realizar el test de permutaciones}
\NormalTok{p\_value\_permutaciones }\OtherTok{\textless{}{-}} \FunctionTok{perm\_test\_multivariante}\NormalTok{(grupo\_acido, grupo\_alcalino)}
\FunctionTok{print}\NormalTok{(p\_value\_permutaciones)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1e-05
\end{verbatim}

El test de permutanciones da un pvalor de 1e-05 para 100000
permutaciones, este es un pvalor muy pequeño (1e-05\textless0.05) por lo
tanto indica una diferencia muy significativa entre los grupos y nos
permite rechazar la hipótesis nula de que los grupos son iguales en
términos de las variables analizadas. Esto vuelve a concordar con lo
mencionado en el apartado anterior y en los apartados C y D, donde se
observan diferencias significativas en las concentraciones de mercurio
entre los dos grupos.

Esto puede deberse a que en ambientes ácidos el mercurio tiende a estar
más disuelto en su forma iónica (Hg²⁺) o en compuestos como el mercurio
dimetílico (MeHg), que es altamente tóxico. Esto se debe a que el
mercurio se disocia más fácilmente en agua ácida, lo que aumenta su
disponibilidad en el medio acuático. En cambio, en ambientes más
alcalinos (con pH más alto), el mercurio tiende a precipitarse en formas
menos solubles, como Hg(OH)₂, lo que reduce su concentración disponible
en el agua.

\hypertarget{ejercicio-2}{%
\subsection{Ejercicio 2}\label{ejercicio-2}}

\hypertarget{a-1}{%
\subsubsection{A)}\label{a-1}}

\begin{verbatim}
##   carcar corflo faggra ileopa liqsty maggra nyssyl ostvir oxyarb pingla quenig
## 1      1      1      7      9      1      8      0     19      3      1      4
## 2      0      2      3     18     13      6      0     19      2      2      0
## 3      7      4      9     13     14      2      3      7      0      8      1
## 4     21      7      7      2      6      1      3     10      1      0      0
## 5      8      2      4      0      0      3      1      9      0      0      1
## 6      3      4     14      1     24      4      1      4      0      5      0
##   quemic symtin
## 1      3      0
## 2     10      0
## 3     14      2
## 4      8      1
## 5      6      0
## 6      7      0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(vegan)}


\NormalTok{muestra1 }\OtherTok{\textless{}{-}}\NormalTok{ selected\_data[}\DecValTok{1}\NormalTok{, ]  }\CommentTok{\# Primera muestra}
\NormalTok{muestra2 }\OtherTok{\textless{}{-}}\NormalTok{ selected\_data[}\DecValTok{2}\NormalTok{, ]  }\CommentTok{\# Segunda muestra}

\CommentTok{\# Bray{-}Curtis}
\NormalTok{Cij }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{pmin}\NormalTok{(muestra1, muestra2))}

\NormalTok{Si }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(muestra1)}
\NormalTok{Sj }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(muestra2)}

\CommentTok{\# Aplicamos la fórmula de Bray{-}Curtis}
\NormalTok{BC1 }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ Cij) }\SpecialCharTok{/}\NormalTok{ (Si }\SpecialCharTok{+}\NormalTok{ Sj)}

\CommentTok{\#vegdist() manual}
\NormalTok{numerador }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{abs}\NormalTok{(muestra1 }\SpecialCharTok{{-}}\NormalTok{ muestra2))}

\NormalTok{denominador }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(muestra1 }\SpecialCharTok{+}\NormalTok{ muestra2)}

\CommentTok{\# 3. Aplicamos la fórmula de Bray{-}Curtis}
\NormalTok{BC2 }\OtherTok{\textless{}{-}}\NormalTok{ numerador }\SpecialCharTok{/}\NormalTok{ denominador}



\CommentTok{\# Calcular la matriz de disimilitudes usando Bray{-}Curtis}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{vegdist}\NormalTok{(selected\_data, }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{)}

\CommentTok{\# Mostrar la matriz de disimilitudes}
\CommentTok{\#print(dissimilarity\_matrix)}

\CommentTok{\# Extraer la disimilitud entre las dos primeras muestras}
\NormalTok{bray\_vegdist\_first\_two }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(dissimilarity\_matrix)[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}


\FunctionTok{cat}\NormalTok{(}\StringTok{\textquotesingle{}Bray{-}Curtis tiene un valor de:\textquotesingle{}}\NormalTok{,BC1,}\StringTok{\textquotesingle{}}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Bray-Curtis tiene un valor de: 0.3181818
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{\textquotesingle{}Bray{-}Curtis Vegdist manual tiene un valor de:\textquotesingle{}}\NormalTok{,BC2,}\StringTok{\textquotesingle{}}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Bray-Curtis Vegdist manual tiene un valor de: 0.3181818
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Disimilitud entre las dos primeras muestras (vegdist):"}\NormalTok{, bray\_vegdist\_first\_two, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Disimilitud entre las dos primeras muestras (vegdist): 0.3181818
\end{verbatim}

Observamos que la disimilaridad calculada Bray-Curtis normal, el
Bray-Curtis calculado manualmente usando la formula de vegdist y con la
función vegdist() tienen el mismo valor

\hypertarget{b-1}{%
\subsubsection{B)}\label{b-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(vegan)}

\CommentTok{\# Calcular la matriz de disimilitudes}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{vegdist}\NormalTok{(selected\_data, }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{))}

\CommentTok{\# Comprobar la desigualdad triangular para todos los tripletes}
\NormalTok{viola\_triang }\OtherTok{\textless{}{-}} \ConstantTok{FALSE}
\NormalTok{total }\OtherTok{\textless{}{-}}\DecValTok{0}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(selected\_data)) \{}
  \ControlFlowTok{for}\NormalTok{ (j }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(selected\_data)) \{}
    \ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(selected\_data)) \{}
      \ControlFlowTok{if}\NormalTok{ (dissimilarity\_matrix[i, j] }\SpecialCharTok{\textgreater{}}\NormalTok{ dissimilarity\_matrix[i, k] }\SpecialCharTok{+}\NormalTok{ dissimilarity\_matrix[k, j]) \{}
\NormalTok{        total }\OtherTok{\textless{}{-}}\NormalTok{ total }\SpecialCharTok{+} \DecValTok{1}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"Violación encontrada entre las muestras:"}\NormalTok{, i, j, k, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{        viola\_triang }\OtherTok{\textless{}{-}} \ConstantTok{TRUE}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Violación encontrada entre las muestras: 2 15 34 
## Violación encontrada entre las muestras: 6 18 38 
## Violación encontrada entre las muestras: 7 55 20 
## Violación encontrada entre las muestras: 8 27 70 
## Violación encontrada entre las muestras: 9 13 18 
## Violación encontrada entre las muestras: 9 15 34 
## Violación encontrada entre las muestras: 9 23 34 
## Violación encontrada entre las muestras: 9 23 59 
## Violación encontrada entre las muestras: 13 9 18 
## Violación encontrada entre las muestras: 13 42 37 
## Violación encontrada entre las muestras: 13 51 37 
## Violación encontrada entre las muestras: 13 58 37 
## Violación encontrada entre las muestras: 15 2 34 
## Violación encontrada entre las muestras: 15 9 34 
## Violación encontrada entre las muestras: 18 6 38 
## Violación encontrada entre las muestras: 18 23 35 
## Violación encontrada entre las muestras: 18 23 38 
## Violación encontrada entre las muestras: 19 69 54 
## Violación encontrada entre las muestras: 21 48 47 
## Violación encontrada entre las muestras: 21 51 35 
## Violación encontrada entre las muestras: 22 51 35 
## Violación encontrada entre las muestras: 23 9 34 
## Violación encontrada entre las muestras: 23 9 59 
## Violación encontrada entre las muestras: 23 18 35 
## Violación encontrada entre las muestras: 23 18 38 
## Violación encontrada entre las muestras: 24 62 14 
## Violación encontrada entre las muestras: 27 8 70 
## Violación encontrada entre las muestras: 27 48 47 
## Violación encontrada entre las muestras: 42 13 37 
## Violación encontrada entre las muestras: 47 71 63 
## Violación encontrada entre las muestras: 48 21 47 
## Violación encontrada entre las muestras: 48 27 47 
## Violación encontrada entre las muestras: 51 13 37 
## Violación encontrada entre las muestras: 51 21 35 
## Violación encontrada entre las muestras: 51 22 35 
## Violación encontrada entre las muestras: 55 7 20 
## Violación encontrada entre las muestras: 55 57 12 
## Violación encontrada entre las muestras: 57 55 12 
## Violación encontrada entre las muestras: 58 13 37 
## Violación encontrada entre las muestras: 62 24 14 
## Violación encontrada entre las muestras: 69 19 54 
## Violación encontrada entre las muestras: 71 47 63
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\NormalTok{viola\_triang) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"No se encontraron violaciones de la desigualdad triangular en los datos proporcionados.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\FunctionTok{cat}\NormalTok{(}\StringTok{\textquotesingle{}Total de violaciones de la desigualdad triangular:\textquotesingle{}}\NormalTok{,total)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Total de violaciones de la desigualdad triangular: 42
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(vegan)}

\CommentTok{\# Calcular la matriz de disimilitudes de Bray{-}Curtis}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{vegdist}\NormalTok{(selected\_data, }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{))}

\CommentTok{\# Transformar la matriz calculando la raíz cuadrada de los valores}
\NormalTok{sqrt\_dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(dissimilarity\_matrix)}

\CommentTok{\# Comprobar la desigualdad triangular para todos los tripletes con la matriz transformada}
\NormalTok{violations }\OtherTok{\textless{}{-}} \DecValTok{0}  \CommentTok{\# Inicializar el contador de violaciones}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(selected\_data)) \{}
  \ControlFlowTok{for}\NormalTok{ (j }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(selected\_data)) \{}
    \ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(selected\_data)) \{}
      \CommentTok{\# Verificar si se cumple la desigualdad triangular}
      \ControlFlowTok{if}\NormalTok{ (sqrt\_dissimilarity\_matrix[i, j] }\SpecialCharTok{\textgreater{}}\NormalTok{ sqrt\_dissimilarity\_matrix[i, k] }\SpecialCharTok{+}\NormalTok{ sqrt\_dissimilarity\_matrix[k, j]) \{}
\NormalTok{        violations }\OtherTok{\textless{}{-}}\NormalTok{ violations }\SpecialCharTok{+} \DecValTok{1}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"Violación encontrada entre las muestras (raíz cuadrada):"}\NormalTok{, i, j, k, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{\}}

\CommentTok{\# Mostrar el número total de violaciones}
\ControlFlowTok{if}\NormalTok{ (violations }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"No se encontraron violaciones de la desigualdad triangular con la raíz cuadrada.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Número total de violaciones con la raíz cuadrada:"}\NormalTok{, violations, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## No se encontraron violaciones de la desigualdad triangular con la raíz cuadrada.
\end{verbatim}

\hypertarget{c-1}{%
\subsubsection{C)}\label{c-1}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cargar los paquetes necesarios}
\FunctionTok{library}\NormalTok{(vegan)}
\FunctionTok{library}\NormalTok{(ape)}

\CommentTok{\# Calcular la matriz de disimilitudes de Bray{-}Curtis}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{vegdist}\NormalTok{(selected\_data, }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{))}

\CommentTok{\# Calcular la raíz cuadrada de la matriz de disimilitudes}
\NormalTok{sqrt\_dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(dissimilarity\_matrix)}

\CommentTok{\# Verificar si es una distancia euclídea mediante PCoA}
\NormalTok{pcoa\_result }\OtherTok{\textless{}{-}} \FunctionTok{pcoa}\NormalTok{(}\FunctionTok{as.dist}\NormalTok{(sqrt\_dissimilarity\_matrix))}

\CommentTok{\# Mostrar los valores propios (eigenvalues)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Valores propios del PCoA:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Valores propios del PCoA:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(pcoa\_result}\SpecialCharTok{$}\NormalTok{values}\SpecialCharTok{$}\NormalTok{Eigenvalues)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 2.91780929 1.97832745 1.23776998 1.03406980 0.89439982 0.68658635
##  [7] 0.61596272 0.55847496 0.54524460 0.47692864 0.41236079 0.39474174
## [13] 0.35412032 0.32212426 0.30173739 0.28716727 0.26754528 0.24963867
## [19] 0.22538013 0.20156301 0.19490286 0.19253288 0.17303134 0.15941751
## [25] 0.15152752 0.14794430 0.13935978 0.13600296 0.12237655 0.11309030
## [31] 0.10604104 0.10454818 0.09799675 0.09344871 0.08854346 0.08594640
## [37] 0.08052466 0.07772224 0.07250774 0.07175633 0.06676822 0.06398925
## [43] 0.05910887 0.05749300 0.05527629 0.05187604 0.04830375 0.04718889
## [49] 0.04433088 0.04242197 0.04143854 0.03945845 0.03749070 0.03279404
## [55] 0.03146384 0.03111680 0.02898234 0.02695166 0.02605387 0.02415237
## [61] 0.02363381 0.02253759 0.02195830 0.01921645 0.01793424 0.01767082
## [67] 0.01668910 0.01577812 0.01355291 0.01262272 0.01196108
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Verificar si todos los valores propios son no negativos}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{all}\NormalTok{(pcoa\_result}\SpecialCharTok{$}\NormalTok{values}\SpecialCharTok{$}\NormalTok{Eigenvalues }\SpecialCharTok{\textgreater{}=} \SpecialCharTok{{-}}\FloatTok{1e{-}10}\NormalTok{)) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"La raíz cuadrada de la disimilitud de Bray{-}Curtis es una distancia euclídea.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"La raíz cuadrada de la disimilitud de Bray{-}Curtis NO es una distancia euclídea.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## La raíz cuadrada de la disimilitud de Bray-Curtis es una distancia euclídea.
\end{verbatim}

Para comprobar si la raíz cuadrada de la disimilitud de Bray-Curtis es
una distancia euclídea, utilizamos el análisis de coordenadas
principales (PCoA), que descompone una matriz de distancias en valores
propios y coordenadas en un espacio euclidiano. Si todos los valores
propios obtenidos son no negativos (o cercanos a cero considerando
errores numéricos), la matriz transformada es euclidiana.

Este análisis se realiza calculando la matriz de disimilitudes de
Bray-Curtis, aplicando la raíz cuadrada a sus valores y verificando los
valores propios mediante la función pcoa() del paquete ape en R. En
general, la raíz cuadrada de la disimilitud de Bray-Curtis cumple esta
propiedad.

\hypertarget{d-1}{%
\subsubsection{D)}\label{d-1}}

\begin{verbatim}
## Warning: package 'factoextra' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Estadístico de Hopkins: 0.679584
\end{verbatim}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-24-1.pdf} El
estadístico de Hopkins (0.679584) es relativamente alto (cercano a 0.70)
y por lo tanto indica que los grupos estarán bastante bien formados. Tal
y como vemos en el gráfico se pueden diferenciar claramente 3 clústeres
en los que quedan agrupados y bien diferenciados todos los datos.

\hypertarget{e-1}{%
\subsubsection{E)}\label{e-1}}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-25-1.pdf} En
el dendograma se aprecia la creación de 3 grandes grupos. Estas 3
grandes agrupaciones concuerdan con el anterior cluster plot donde
también se generan 3 grandes agrupaciones en las que se pueden
clasificar todas las muestras.

\includegraphics{project_2_files/figure-latex/unnamed-chunk-26-1.pdf}

El heatmap sirve para poder comparar muestras y discernir visualmente
mediante una escala de colores cuales se parecen más (azul) y cuales se
parecen menos (blanco) entre ellas. Esto tambien permite crear
agrupaciones en nuestras muestras mediante colores.

Por ejemplo en el heatmap podemos ver que las muestras 47 y 48 son
parecidas a las muestras 61 y 62, si observamos la composición de
árboles de las muestras 47vs61 y 48vs62 podemos ver que es bastante
parecida con una gran predominancia de `carcar', `liqsty' y `quemic'.

\hypertarget{f-1}{%
\subsubsection{F)}\label{f-1}}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-27-1.pdf}

Con el metodo silhouette se observa claramente que el número óptimo de
clusters es 3, tal y como indica el cluster plot del apartado D.

\includegraphics{project_2_files/figure-latex/unnamed-chunk-28-1.pdf}

Con el método WSS no está tan claro cual es el número óptimo de
clústers, ya que el gráfico no muestra ningún codo claro donde el total
within sum of square caiga drásticamente.

\hypertarget{g-1}{%
\subsubsection{G)}\label{g-1}}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-29-1.pdf}

Con el método PAM el número óptimo de conglomerados es de 2
conglomerados.

Los 3 criterios anteriores han dado respuestas diferentes, con lo que no
podemos conluir que haya un número claro de conglomerados óptimo para
clusterizar los datos con la información que disponemos ahora. Hacen
falta análisis más profundos o disponer de algún criterio experto para
poder determinar con certeza cuál es el mejor número de clústeres.

\hypertarget{h-1}{%
\subsubsection{H)}\label{h-1}}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-30-1.pdf}

\begin{verbatim}
##   carcar faggra ileopa liqsty maggra ostvir quenig quemic
## 1      1   10.0    9.0    6.0    6.0    7.0      1      4
## 2      0    4.0   18.0    8.0    0.0   18.0      0      4
## 3      7    6.0    4.0   10.0    3.0    6.0      1      5
## 4      8   13.0    3.5    3.5    5.0    0.5      0      6
## 5      1   15.0    6.0    2.0    6.0    3.0      0      0
## 6     21    4.5    2.5    6.0    2.5    1.0      5     10
\end{verbatim}

\begin{verbatim}
## 
## Call:
## cca(X = medians_filtered) 
## 
## Partitioning of scaled Chi-square:
##               Inertia Proportion
## Total          0.5508          1
## Unconstrained  0.5508          1
## 
## Eigenvalues, and their contribution to the scaled Chi-square 
## 
## Importance of components:
##                          CA1    CA2     CA3     CA4      CA5
## Eigenvalue            0.3327 0.1791 0.02103 0.01263 0.005463
## Proportion Explained  0.6039 0.3251 0.03818 0.02292 0.009919
## Cumulative Proportion 0.6039 0.9290 0.96716 0.99008 1.000000
\end{verbatim}

\includegraphics{project_2_files/figure-latex/unnamed-chunk-31-1.pdf}

El análisis de correspondencias nos muestra como se agrupan las
variables en función la mediana de las frecuencias en los 6
conglomerados. Podemos observar que las variables con una menor
distancia en el gráfico son `faggra' y `maggra'. Lo cual sugiere que su
composición de medianas de las frecuencias en los conglomerados son las
más parecidas de entre todo el conjunto de datos.

\hypertarget{annexos}{%
\subsection{ANNEXOS}\label{annexos}}

\hypertarget{ejercicio-1-1}{%
\subsubsection{Ejercicio 1}\label{ejercicio-1-1}}

\hypertarget{a-2}{%
\paragraph{A)}\label{a-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Especificamos path}
\NormalTok{file\_path }\OtherTok{\textless{}{-}} \StringTok{"MERCBASS.txt"}

\CommentTok{\# Cargamos los datos}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.delim}\NormalTok{(file\_path, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep =} \StringTok{"}\SpecialCharTok{\textbackslash{}t}\StringTok{"}\NormalTok{)}

\CommentTok{\# Visualizamos}
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\hypertarget{b-2}{%
\paragraph{B)}\label{b-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcular el número total de lagos}
\NormalTok{total\_lagos }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df)}

\CommentTok{\# Contar los lagos con Avg Mercury \textgreater{} 0.5}
\NormalTok{lagos\_no\_saludables }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Avg.Mercury }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{)}

\CommentTok{\# Calcular el porcentaje}
\NormalTok{porcentaje\_no\_saludables }\OtherTok{\textless{}{-}}\NormalTok{ (lagos\_no\_saludables }\SpecialCharTok{/}\NormalTok{ total\_lagos) }\SpecialCharTok{*} \DecValTok{100}

\CommentTok{\# Mostrar resultados}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Porcentaje de lagos con niveles no saludables de mercurio:"}\NormalTok{, porcentaje\_no\_saludables, }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{c-2}{%
\paragraph{C)}\label{c-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Seleccionar las variables de interés}
\NormalTok{variables\_interes }\OtherTok{\textless{}{-}}\NormalTok{ df[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Alkalinity"}\NormalTok{, }\StringTok{"pH"}\NormalTok{, }\StringTok{"Calcium"}\NormalTok{, }\StringTok{"Chlorophyll"}\NormalTok{, }\StringTok{"Avg.Mercury"}\NormalTok{)]}

\CommentTok{\# Crear la matriz de diagramas de dispersión}
\FunctionTok{pairs}\NormalTok{(variables\_interes, }\AttributeTok{main =} \StringTok{"Relación entre variables químicas y concentración de mercurio"}\NormalTok{,}
      \AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{)}


\FunctionTok{plot}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Alkalinity, df}\SpecialCharTok{$}\NormalTok{Avg.Mercury, }\AttributeTok{main=}\StringTok{"Relación entre Alkalinity y Avg Mercury"}\NormalTok{, }
     \AttributeTok{xlab=}\StringTok{"Alkalinity (mg/l)"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Avg Mercury (ppm)"}\NormalTok{, }\AttributeTok{pch=}\DecValTok{19}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(Avg.Mercury }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Alkalinity, }\AttributeTok{data=}\NormalTok{df), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)  }\CommentTok{\# Línea de regresión}
\end{Highlighting}
\end{Shaded}

\hypertarget{d-2}{%
\paragraph{D)}\label{d-2}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rcompanion)}
\CommentTok{\# Seleccionar las variables químicas y la concentración de mercurio}
\NormalTok{variables }\OtherTok{\textless{}{-}}\NormalTok{ df[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Alkalinity"}\NormalTok{, }\StringTok{"pH"}\NormalTok{, }\StringTok{"Calcium"}\NormalTok{, }\StringTok{"Chlorophyll"}\NormalTok{, }\StringTok{"Avg.Mercury"}\NormalTok{)]}

\CommentTok{\# Transformar cada variable con Tukey}
\NormalTok{variables\_trans }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(variables, }\ControlFlowTok{function}\NormalTok{(x) \{}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.numeric}\NormalTok{(x)) \{}
    \FunctionTok{transformTukey}\NormalTok{(x, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{)  }\CommentTok{\# Aplicar la transformación sin graficar}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{    x  }\CommentTok{\# Si no es numérica, mantenerla igual}
\NormalTok{  \}}
\NormalTok{\}))}

\CommentTok{\# Renombrar columnas para identificarlas como transformadas}
\FunctionTok{colnames}\NormalTok{(variables\_trans) }\OtherTok{\textless{}{-}} \FunctionTok{paste0}\NormalTok{(}\FunctionTok{colnames}\NormalTok{(variables), }\StringTok{"\_trans"}\NormalTok{)}

\CommentTok{\# Seleccionar las variables de interés}
\NormalTok{variables\_interes\_trans }\OtherTok{\textless{}{-}}\NormalTok{ variables\_trans[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Alkalinity\_trans"}\NormalTok{, }\StringTok{"pH\_trans"}\NormalTok{, }\StringTok{"Calcium\_trans"}\NormalTok{, }\StringTok{"Chlorophyll\_trans"}\NormalTok{, }\StringTok{"Avg.Mercury\_trans"}\NormalTok{)]}

\CommentTok{\# Crear la matriz de diagramas de dispersión}
\FunctionTok{pairs}\NormalTok{(variables\_interes\_trans, }\AttributeTok{main =} \StringTok{"Relación entre variables químicas y concentración de mercurio"}\NormalTok{,}
      \AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{e-2}{%
\paragraph{E)}\label{e-2}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rcompanion)}

\CommentTok{\# Transformar las variables químicas (X1, X2, X3, X4) y las de mercurio (Y1, Y2, Y3)}
\NormalTok{variables\_transformadas }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{X1 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Alkalinity, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{X2 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{pH, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{X3 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Calcium, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{X4 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Chlorophyll, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{Y1 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Min, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{Y2 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Avg.Mercury, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{),}
  \AttributeTok{Y3 =} \FunctionTok{transformTukey}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Max, }\AttributeTok{plotit =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{)}

\CommentTok{\# Calcular la matriz de centrado H}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(variables\_transformadas)  }\CommentTok{\# Número de observaciones}
\NormalTok{H }\OtherTok{\textless{}{-}} \FunctionTok{diag}\NormalTok{(n) }\SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ n) }\SpecialCharTok{*} \FunctionTok{matrix}\NormalTok{(}\DecValTok{1}\NormalTok{, n, n)  }\CommentTok{\# Matriz de centrado}

\CommentTok{\# Centrar las variables manualmente (restar la media de cada columna)}
\NormalTok{variables\_centradas }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(variables\_transformadas, }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Calcular la matriz de varianzas{-}covarianzas manualmente}
\NormalTok{var\_cov\_manual }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{*} \FunctionTok{t}\NormalTok{(variables\_centradas) }\SpecialCharTok{\%*\%}\NormalTok{ variables\_centradas}

\CommentTok{\# Comparar con la función cov()}
\NormalTok{var\_cov\_func }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(variables\_transformadas)}

\CommentTok{\# Verificar si los resultados coinciden}
\FunctionTok{all.equal}\NormalTok{(var\_cov\_manual, var\_cov\_func)}
\end{Highlighting}
\end{Shaded}

\hypertarget{f-2}{%
\paragraph{F)}\label{f-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cálculo de las medias}
\NormalTok{media\_X }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(variables\_transformadas[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{])  }\CommentTok{\# Medias de X1, X2, X3, X4}
\NormalTok{media\_Y }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(variables\_transformadas[, }\DecValTok{5}\SpecialCharTok{:}\DecValTok{7}\NormalTok{])  }\CommentTok{\# Medias de Y1, Y2, Y3}

\CommentTok{\# Cálculo de las varianzas}
\NormalTok{var\_X }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(variables\_transformadas[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{], }\DecValTok{2}\NormalTok{, var)  }\CommentTok{\# Varianzas de X1, X2, X3, X4}
\NormalTok{var\_Y }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(variables\_transformadas[, }\DecValTok{5}\SpecialCharTok{:}\DecValTok{7}\NormalTok{], }\DecValTok{2}\NormalTok{, var)  }\CommentTok{\# Varianzas de Y1, Y2, Y3}

\CommentTok{\# Cálculo de las covarianzas}
\NormalTok{cov\_X }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(variables\_transformadas[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{])  }\CommentTok{\# Covarianzas entre X1, X2, X3, X4}
\NormalTok{cov\_Y }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(variables\_transformadas[, }\DecValTok{5}\SpecialCharTok{:}\DecValTok{7}\NormalTok{])  }\CommentTok{\# Covarianzas entre Y1, Y2, Y3}
\NormalTok{cov\_XY }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(variables\_transformadas[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{], variables\_transformadas[, }\DecValTok{5}\SpecialCharTok{:}\DecValTok{7}\NormalTok{])  }\CommentTok{\# Covarianzas entre X y Y}

\CommentTok{\# Cálculo de la media de U y V}
\CommentTok{\# U = 0.4*X1 + 0.2*X2 + 0.2*X3 + 0.2*X4}
\CommentTok{\# V = (Y1 + Y2 + Y3) / 3}
\NormalTok{mu\_U }\OtherTok{\textless{}{-}} \FloatTok{0.4} \SpecialCharTok{*}\NormalTok{ media\_X[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ media\_X[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ media\_X[}\DecValTok{3}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ media\_X[}\DecValTok{4}\NormalTok{]}
\NormalTok{mu\_V }\OtherTok{\textless{}{-}}\NormalTok{ (media\_Y[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ media\_Y[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ media\_Y[}\DecValTok{3}\NormalTok{]) }\SpecialCharTok{/} \DecValTok{3}

\CommentTok{\# Cálculo de la varianza de U}
\NormalTok{var\_U }\OtherTok{\textless{}{-}} \FloatTok{0.4}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ var\_X[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ var\_X[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ var\_X[}\DecValTok{3}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ var\_X[}\DecValTok{4}\NormalTok{] }\SpecialCharTok{+}
  \DecValTok{2} \SpecialCharTok{*}\NormalTok{ (}\FloatTok{0.4} \SpecialCharTok{*} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_X[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.4} \SpecialCharTok{*} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_X[}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.4} \SpecialCharTok{*} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_X[}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{] }\SpecialCharTok{+}
  \FloatTok{0.2} \SpecialCharTok{*} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_X[}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_X[}\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_X[}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{])}

\CommentTok{\# Cálculo de la varianza de V}
\NormalTok{var\_V }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\DecValTok{9}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (var\_Y[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ var\_Y[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ var\_Y[}\DecValTok{3}\NormalTok{] }\SpecialCharTok{+} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ (cov\_Y[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ cov\_Y[}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{] }\SpecialCharTok{+}\NormalTok{ cov\_Y[}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{]))}

\CommentTok{\# Cálculo de la covarianza entre U y V}
\NormalTok{cov\_UV }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (}\FloatTok{0.4} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.4} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.4} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{] }\SpecialCharTok{+}
                  \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{] }\SpecialCharTok{+}
                  \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{3}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{3}\NormalTok{, }\DecValTok{3}\NormalTok{] }\SpecialCharTok{+}
                  \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{4}\NormalTok{, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{4}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{+} \FloatTok{0.2} \SpecialCharTok{*}\NormalTok{ cov\_XY[}\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{])}

\CommentTok{\# Cálculo de la correlación entre U y V}
\NormalTok{corr\_UV }\OtherTok{\textless{}{-}}\NormalTok{ cov\_UV }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(var\_U }\SpecialCharTok{*}\NormalTok{ var\_V)}

\CommentTok{\# Resultados}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Media de U: "}\NormalTok{, mu\_U, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Media de V: "}\NormalTok{, mu\_V, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Varianza de U: "}\NormalTok{, var\_U, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Varianza de V: "}\NormalTok{, var\_V, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlación entre U y V: "}\NormalTok{, corr\_UV, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{g-2}{%
\paragraph{G)}\label{g-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Quitamos ph neutro de los datasets}

\NormalTok{indices\_ph\_7 }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{pH }\SpecialCharTok{==} \DecValTok{7}\NormalTok{)}
\NormalTok{df\_sin\_ph\_7 }\OtherTok{\textless{}{-}}\NormalTok{ df[}\SpecialCharTok{{-}}\NormalTok{indices\_ph\_7, ]}
\NormalTok{variables\_transformadas\_sin\_ph\_7 }\OtherTok{\textless{}{-}}\NormalTok{ variables\_transformadas[}\SpecialCharTok{{-}}\NormalTok{indices\_ph\_7, ]}


\CommentTok{\# Clasificar los valores de pH según la condición}
\NormalTok{variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH }\SpecialCharTok{\textless{}} \DecValTok{7}\NormalTok{, }\StringTok{"Ácido"}\NormalTok{, }\CommentTok{\#detectamos ph en el df\_sin\_ph\_7 y aplicamos cambios}
                      \FunctionTok{ifelse}\NormalTok{(df\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH }\SpecialCharTok{\textgreater{}} \DecValTok{7}\NormalTok{, }\StringTok{"Alcalino"}\NormalTok{, }\ConstantTok{NA}\NormalTok{))                 }\CommentTok{\#en variables transformadas}


\CommentTok{\# usar pivot\_longer para transformar las columnas Y1, Y2, Y3 a un formato largo}
\FunctionTok{library}\NormalTok{(tidyr)}

\CommentTok{\# Transformamos el dataframe a formato largo}
\NormalTok{data\_larga }\OtherTok{\textless{}{-}}\NormalTok{ variables\_transformadas\_sin\_ph\_7 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols =} \FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{), }
               \AttributeTok{names\_to =} \StringTok{"variable"}\NormalTok{, }
               \AttributeTok{values\_to =} \StringTok{"value"}\NormalTok{)}

\CommentTok{\# Verificamos el resultado}
\CommentTok{\#head(data\_larga)}

\CommentTok{\# Graficar el boxplot múltiple comparando los valores de Y1, Y2, Y3 entre los grupos Ácido y Alcalino}
\FunctionTok{boxplot}\NormalTok{(value }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pH\_grupo }\SpecialCharTok{*}\NormalTok{ variable, }
        \AttributeTok{data =}\NormalTok{ data\_larga,}
        \AttributeTok{main =} \StringTok{"Comparación de Y1, Y2, Y3 entre lagos ácidos y alcalinos"}\NormalTok{,}
        \AttributeTok{xlab =} \StringTok{"Grupo de pH y Variable"}\NormalTok{, }
        \AttributeTok{ylab =} \StringTok{"Valor de las Variables"}\NormalTok{,}
        \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"lightblue"}\NormalTok{, }\StringTok{"lightgreen"}\NormalTok{), }
        \AttributeTok{las =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{h-2}{%
\paragraph{H)}\label{h-2}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(MVN)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(ggpubr)}

\CommentTok{\# Lista de variables a analizar}
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)}

\CommentTok{\# Crear QQ{-}Plots para cada variable en los grupos Ácido y Alcalino}
\NormalTok{plots }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (var }\ControlFlowTok{in}\NormalTok{ variables) \{}
\NormalTok{  plot\_acido }\OtherTok{\textless{}{-}} \FunctionTok{ggqqplot}\NormalTok{(variables\_transformadas\_sin\_ph\_7[[var]][variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Ácido"}\NormalTok{], }
                         \AttributeTok{main =} \FunctionTok{paste}\NormalTok{(}\StringTok{"QQ{-}Plot"}\NormalTok{, var, }\StringTok{"(Ácidos)"}\NormalTok{))}
\NormalTok{  plot\_alcalino }\OtherTok{\textless{}{-}} \FunctionTok{ggqqplot}\NormalTok{(variables\_transformadas\_sin\_ph\_7[[var]][variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Alcalino"}\NormalTok{], }
                            \AttributeTok{main =} \FunctionTok{paste}\NormalTok{(}\StringTok{"QQ{-}Plot"}\NormalTok{, var, }\StringTok{"(Alcalinos)"}\NormalTok{))}
\NormalTok{  plots }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(plots, }\FunctionTok{list}\NormalTok{(plot\_acido, plot\_alcalino))}
\NormalTok{\}}

\CommentTok{\# Mostrar los QQ{-}Plots en una cuadrícula}
\FunctionTok{ggarrange}\NormalTok{(}\AttributeTok{plotlist =}\NormalTok{ plots, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{nrow =} \FunctionTok{length}\NormalTok{(variables))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lista de variables a analizar}
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)  }\CommentTok{\# Agrega aquí todas las variables relevantes}

\CommentTok{\# Crear una lista para almacenar los resultados}
\NormalTok{resultados\_shapiro }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}

\CommentTok{\# Test de Shapiro{-}Wilk para cada variable en cada grupo}
\ControlFlowTok{for}\NormalTok{ (var }\ControlFlowTok{in}\NormalTok{ variables) \{}
\NormalTok{  resultado\_acido }\OtherTok{\textless{}{-}} \FunctionTok{shapiro.test}\NormalTok{(variables\_transformadas\_sin\_ph\_7[[var]][variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Ácido"}\NormalTok{])}
\NormalTok{  resultado\_alcalino }\OtherTok{\textless{}{-}} \FunctionTok{shapiro.test}\NormalTok{(variables\_transformadas\_sin\_ph\_7[[var]][variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Alcalino"}\NormalTok{])}
  
  \CommentTok{\# Guardar los resultados en una lista}
\NormalTok{  resultados\_shapiro[[}\FunctionTok{paste}\NormalTok{(var, }\StringTok{"Ácido"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"\_"}\NormalTok{)]] }\OtherTok{\textless{}{-}}\NormalTok{ resultado\_acido}
\NormalTok{  resultados\_shapiro[[}\FunctionTok{paste}\NormalTok{(var, }\StringTok{"Alcalino"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"\_"}\NormalTok{)]] }\OtherTok{\textless{}{-}}\NormalTok{ resultado\_alcalino}
\NormalTok{\}}

\CommentTok{\# Mostrar los resultados}
\ControlFlowTok{for}\NormalTok{ (nombre }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(resultados\_shapiro)) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Resultados para"}\NormalTok{, nombre, }\StringTok{":}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{print}\NormalTok{(resultados\_shapiro[[nombre]])}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filtrar los datos para los grupos "Ácido" y "Alcalino"}
\NormalTok{data\_acido }\OtherTok{\textless{}{-}}\NormalTok{ variables\_transformadas\_sin\_ph\_7[variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Ácido"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)]}
\NormalTok{data\_alcalino }\OtherTok{\textless{}{-}}\NormalTok{ variables\_transformadas\_sin\_ph\_7[variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Alcalino"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)]}

\CommentTok{\# Realizar el análisis de normalidad multivariante para el grupo Ácido}
\NormalTok{resultados\_mvn\_acido }\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_acido)}
\NormalTok{resultados\_mvn\_acido}

\CommentTok{\# Realizar el análisis de normalidad multivariante para el grupo Alcalino}
\NormalTok{resultados\_mvn\_alcalino }\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_alcalino)}
\NormalTok{resultados\_mvn\_alcalino}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcular la matriz de covarianzas y medias de las variables}
\NormalTok{mean\_vals }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(variables\_transformadas\_sin\_ph\_7[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)])}
\NormalTok{cov\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(variables\_transformadas\_sin\_ph\_7[, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)])}

\CommentTok{\# Calcular las distancias de Mahalanobis para los grupos Ácidos y Alcalinos}
\NormalTok{mahal\_ácidos }\OtherTok{\textless{}{-}} \FunctionTok{mahalanobis}\NormalTok{(}
\NormalTok{  variables\_transformadas\_sin\_ph\_7[variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Ácido"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)],}
  \AttributeTok{center =}\NormalTok{ mean\_vals,}
  \AttributeTok{cov =}\NormalTok{ cov\_matrix}
\NormalTok{)}

\NormalTok{mahal\_alcalinos }\OtherTok{\textless{}{-}} \FunctionTok{mahalanobis}\NormalTok{(}
\NormalTok{  variables\_transformadas\_sin\_ph\_7[variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Alcalino"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)],}
  \AttributeTok{center =}\NormalTok{ mean\_vals,}
  \AttributeTok{cov =}\NormalTok{ cov\_matrix}
\NormalTok{)}

\CommentTok{\# Graficar los QQ{-}plots de las distancias de Mahalanobis}
\CommentTok{\# Ácidos}
\FunctionTok{qqplot}\NormalTok{(}
  \FunctionTok{qchisq}\NormalTok{(}\FunctionTok{ppoints}\NormalTok{(}\FunctionTok{length}\NormalTok{(mahal\_ácidos)), }\AttributeTok{df =} \DecValTok{3}\NormalTok{), mahal\_ácidos,}
  \AttributeTok{main =} \StringTok{"QQ{-}Plot Mahalanobis Distances (Ácidos)"}\NormalTok{,}
  \AttributeTok{xlab =} \StringTok{"Teórica Chi{-}cuadrado"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Distancias Mahalanobis"}
\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)  }\CommentTok{\# Agregar la línea diagonal}

\CommentTok{\# Alcalinos}
\FunctionTok{qqplot}\NormalTok{(}
  \FunctionTok{qchisq}\NormalTok{(}\FunctionTok{ppoints}\NormalTok{(}\FunctionTok{length}\NormalTok{(mahal\_alcalinos)), }\AttributeTok{df =} \DecValTok{3}\NormalTok{), mahal\_alcalinos,}
  \AttributeTok{main =} \StringTok{"QQ{-}Plot Mahalanobis Distances (Alcalinos)"}\NormalTok{,}
  \AttributeTok{xlab =} \StringTok{"Teórica Chi{-}cuadrado"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Distancias Mahalanobis"}
\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)  }\CommentTok{\# Agregar la línea diagonal}
\end{Highlighting}
\end{Shaded}

\hypertarget{i-1}{%
\paragraph{I)}\label{i-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(heplots)}

\CommentTok{\# Nos aseguramos de que \textquotesingle{}pH\_grupo\textquotesingle{} sea un factor}
\NormalTok{variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo)}

\CommentTok{\# test M de Box}
\NormalTok{test\_m\_box }\OtherTok{\textless{}{-}} \FunctionTok{boxM}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(Y1, Y2, Y3) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pH\_grupo, }\AttributeTok{data =}\NormalTok{ variables\_transformadas\_sin\_ph\_7)}
\NormalTok{test\_m\_box}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#El test de levene multivariado da un error persistente que no me permite avanzar, para realizar las comparaciones haré el test de levene univariado para las 3 variables}

\FunctionTok{library}\NormalTok{(car)}

\CommentTok{\# Test de Levene multivariado}
\CommentTok{\#levene\_test \textless{}{-} leveneTest(cbind(Y1, Y2, Y3) \textasciitilde{} pH\_grupo, data = variables\_transformadas\_sin\_ph\_7)}
\CommentTok{\#print(levene\_test)}



\CommentTok{\# Test de Levene para cada variable por separado}
\NormalTok{levene\_test\_Y1 }\OtherTok{\textless{}{-}} \FunctionTok{leveneTest}\NormalTok{(Y1 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pH\_grupo, }\AttributeTok{data =}\NormalTok{ variables\_transformadas\_sin\_ph\_7)}
\NormalTok{levene\_test\_Y2 }\OtherTok{\textless{}{-}} \FunctionTok{leveneTest}\NormalTok{(Y2 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pH\_grupo, }\AttributeTok{data =}\NormalTok{ variables\_transformadas\_sin\_ph\_7)}
\NormalTok{levene\_test\_Y3 }\OtherTok{\textless{}{-}} \FunctionTok{leveneTest}\NormalTok{(Y3 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pH\_grupo, }\AttributeTok{data =}\NormalTok{ variables\_transformadas\_sin\_ph\_7)}

\CommentTok{\# Imprimir resultados}
\FunctionTok{print}\NormalTok{(levene\_test\_Y1)}
\FunctionTok{print}\NormalTok{(levene\_test\_Y2)}
\FunctionTok{print}\NormalTok{(levene\_test\_Y3)}
\end{Highlighting}
\end{Shaded}

\hypertarget{j-1}{%
\paragraph{J)}\label{j-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ICSNP)}
\FunctionTok{library}\NormalTok{(Hotelling)}

\CommentTok{\# Filtrar los datos para los grupos Ácido y Alcalino}
\NormalTok{grupo\_acido }\OtherTok{\textless{}{-}}\NormalTok{ variables\_transformadas\_sin\_ph\_7[variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Ácido"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)]}
\NormalTok{grupo\_alcalino }\OtherTok{\textless{}{-}}\NormalTok{ variables\_transformadas\_sin\_ph\_7[variables\_transformadas\_sin\_ph\_7}\SpecialCharTok{$}\NormalTok{pH\_grupo }\SpecialCharTok{==} \StringTok{"Alcalino"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"Y1"}\NormalTok{, }\StringTok{"Y2"}\NormalTok{, }\StringTok{"Y3"}\NormalTok{)]}

\CommentTok{\# Realizar el test de Hotelling T²}
\NormalTok{hotelling\_test }\OtherTok{\textless{}{-}} \FunctionTok{hotelling.test}\NormalTok{(grupo\_acido, grupo\_alcalino)}
\FunctionTok{print}\NormalTok{(hotelling\_test)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(perm)}

\CommentTok{\# Crear una función de permutación para la comparación multivariante}
\NormalTok{perm\_test\_multivariante }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(grupo1, grupo2, }\AttributeTok{num\_permutaciones =} \DecValTok{100000}\NormalTok{) \{}
  \CommentTok{\# Calcular la diferencia de medias observada utilizando la norma de la diferencia de medias}
\NormalTok{  diff\_observada }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{sum}\NormalTok{((}\FunctionTok{colMeans}\NormalTok{(grupo1) }\SpecialCharTok{{-}} \FunctionTok{colMeans}\NormalTok{(grupo2))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
  
  \CommentTok{\# Realizar las permutaciones}
\NormalTok{  diferencias\_permutadas }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(num\_permutaciones, \{}
    \CommentTok{\# Permutar las filas de los dos grupos y recalcular la diferencia de medias}
\NormalTok{    datos\_permutados }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(grupo1, grupo2)}
\NormalTok{    indices\_permutados }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(datos\_permutados))}
\NormalTok{    grupo1\_permutado }\OtherTok{\textless{}{-}}\NormalTok{ datos\_permutados[indices\_permutados[}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(grupo1)], ]}
\NormalTok{    grupo2\_permutado }\OtherTok{\textless{}{-}}\NormalTok{ datos\_permutados[indices\_permutados[(}\FunctionTok{nrow}\NormalTok{(grupo1)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(datos\_permutados)], ]}
    \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{sum}\NormalTok{((}\FunctionTok{colMeans}\NormalTok{(grupo1\_permutado) }\SpecialCharTok{{-}} \FunctionTok{colMeans}\NormalTok{(grupo2\_permutado))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{  \})}
  
  \CommentTok{\# Calcular el valor p}
\NormalTok{  p\_value }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(diferencias\_permutadas }\SpecialCharTok{\textgreater{}=}\NormalTok{ diff\_observada)}
  \FunctionTok{return}\NormalTok{(p\_value)}
\NormalTok{\}}

\CommentTok{\# Realizar el test de permutaciones}
\NormalTok{p\_value\_permutaciones }\OtherTok{\textless{}{-}} \FunctionTok{perm\_test\_multivariante}\NormalTok{(grupo\_acido, grupo\_alcalino)}
\FunctionTok{print}\NormalTok{(p\_value\_permutaciones)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ejercicio-2-1}{%
\subsubsection{Ejercicio 2}\label{ejercicio-2-1}}

\hypertarget{a-3}{%
\paragraph{A)}\label{a-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"wood.csv"}\NormalTok{, }\AttributeTok{sep=}\StringTok{","}\NormalTok{)}
\NormalTok{selected\_data }\OtherTok{\textless{}{-}}\NormalTok{ data[}\FunctionTok{c}\NormalTok{(}\StringTok{"carcar"}\NormalTok{, }\StringTok{"corflo"}\NormalTok{, }\StringTok{"faggra"}\NormalTok{, }\StringTok{"ileopa"}\NormalTok{, }\StringTok{"liqsty"}\NormalTok{, }
                        \StringTok{"maggra"}\NormalTok{, }\StringTok{"nyssyl"}\NormalTok{, }\StringTok{"ostvir"}\NormalTok{, }\StringTok{"oxyarb"}\NormalTok{, }\StringTok{"pingla"}\NormalTok{, }
                        \StringTok{"quenig"}\NormalTok{, }\StringTok{"quemic"}\NormalTok{, }\StringTok{"symtin"}\NormalTok{)]}

\CommentTok{\# Ver las primeras filas del dataset seleccionado}
\FunctionTok{head}\NormalTok{(selected\_data)}
\end{Highlighting}
\end{Shaded}

\hypertarget{d-3}{%
\paragraph{D)}\label{d-3}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(factoextra)}

\CommentTok{\# Calcular el estadístico de Hopkins}
\NormalTok{clust\_tendency }\OtherTok{\textless{}{-}} \FunctionTok{get\_clust\_tendency}\NormalTok{(selected\_data, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(selected\_data) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{graph =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Mostrar el valor del estadístico de Hopkins}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Estadístico de Hopkins:"}\NormalTok{, clust\_tendency}\SpecialCharTok{$}\NormalTok{hopkins\_stat, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}

\FunctionTok{library}\NormalTok{(factoextra)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)  }\CommentTok{\# Para reproducibilidad}

\CommentTok{\# Normalizar los datos }
\NormalTok{scaled\_data }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(selected\_data)}

\CommentTok{\# Aplicar k{-}means con 3 clusters (puedes ajustar este número)}
\NormalTok{km\_res }\OtherTok{\textless{}{-}} \FunctionTok{kmeans}\NormalTok{(scaled\_data, }\AttributeTok{centers =} \DecValTok{3}\NormalTok{, }\AttributeTok{nstart =} \DecValTok{25}\NormalTok{)}

\CommentTok{\# Visualizar los clusters}
\FunctionTok{fviz\_cluster}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\AttributeTok{data =}\NormalTok{ scaled\_data, }\AttributeTok{cluster =}\NormalTok{ km\_res}\SpecialCharTok{$}\NormalTok{cluster),}
             \AttributeTok{ellipse.type =} \StringTok{"norm"}\NormalTok{,  }\CommentTok{\# Tipo de elipse para los grupos}
             \AttributeTok{geom =} \StringTok{"point"}\NormalTok{,         }\CommentTok{\# Visualizar puntos}
             \AttributeTok{stand =} \ConstantTok{FALSE}\NormalTok{,          }\CommentTok{\# No volver a estandarizar}
             \AttributeTok{palette =} \StringTok{"jco"}\NormalTok{,        }\CommentTok{\# Paleta de colores}
             \AttributeTok{ggtheme =} \FunctionTok{theme\_classic}\NormalTok{())  }\CommentTok{\# Tema gráfico clásico}
\end{Highlighting}
\end{Shaded}

\hypertarget{e-3}{%
\paragraph{E)}\label{e-3}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cargar los paquetes necesarios}
\FunctionTok{library}\NormalTok{(vegan)}
\FunctionTok{library}\NormalTok{(cluster)}

\CommentTok{\# Calcular la matriz de disimilitud de Bray{-}Curtis}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{vegdist}\NormalTok{(selected\_data, }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{)}

\CommentTok{\# Aplicar la transformación de raíz cuadrada para garantizar la euclideidad}
\NormalTok{sqrt\_dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(dissimilarity\_matrix)}

\CommentTok{\# Realizar el análisis de conglomerados jerárquico con el método de Ward}
\CommentTok{\# Nota: hclust() requiere un objeto de clase "dist"}
\NormalTok{hc\_ward }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(}\FunctionTok{as.dist}\NormalTok{(sqrt\_dissimilarity\_matrix), }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}

\CommentTok{\# Dibujar el dendrograma}
\FunctionTok{plot}\NormalTok{(hc\_ward, }\AttributeTok{main =} \StringTok{"Dendrograma del análisis jerárquico (Ward)"}\NormalTok{, }
     \AttributeTok{sub =} \StringTok{""}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Muestras"}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{hang =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)}

\FunctionTok{heatmap}\NormalTok{(dissimilarity\_matrix,}
        \AttributeTok{distfun =} \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{as.dist}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{vegdist}\NormalTok{(x, }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{)))), }\CommentTok{\# Función para calcular la disimilitud}
        \AttributeTok{hclustfun =} \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{hclust}\NormalTok{(x, }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{), }\CommentTok{\# Método de clustering (Ward)}
        \AttributeTok{col =} \FunctionTok{colorRampPalette}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"white"}\NormalTok{))(}\DecValTok{100}\NormalTok{), }\CommentTok{\# Escala de colores}
        \AttributeTok{scale =} \StringTok{"none"}\NormalTok{, }\CommentTok{\# No reescalar los datos}
        \AttributeTok{main =} \StringTok{"Heatmap del análisis jerárquico de Bray{-}Curtis"}\NormalTok{,}
        \AttributeTok{xlab =} \StringTok{"Especies"}\NormalTok{, }\CommentTok{\# Etiqueta eje X}
        \AttributeTok{ylab =} \StringTok{"Muestras"}\NormalTok{,}
        \AttributeTok{Rowv =} \ConstantTok{NA}\NormalTok{,         }\CommentTok{\# No reordenar las filas}
        \AttributeTok{Colv =} \ConstantTok{NA}\NormalTok{,}
\NormalTok{        ) }\CommentTok{\# Etiqueta eje Y}
\end{Highlighting}
\end{Shaded}

\hypertarget{f-3}{%
\paragraph{F)}\label{f-3}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(factoextra)}
\FunctionTok{library}\NormalTok{(vegan)}
\FunctionTok{library}\NormalTok{(fpc)}

\CommentTok{\# Calcular la disimilitud de Bray{-}Curtis y luego aplicar la raíz cuadrada}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{vegdist}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(selected\_data)), }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{)}

\CommentTok{\# Realizar el análisis jerárquico}
\NormalTok{hc }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(dissimilarity\_matrix, }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}

\CommentTok{\# Determinar el número óptimo de clusters usando el criterio de las siluetas}
\FunctionTok{fviz\_nbclust}\NormalTok{(selected\_data, }
             \AttributeTok{FUNcluster =}\NormalTok{ hcut,           }\CommentTok{\# Usamos hcut para cortar el dendrograma}
             \AttributeTok{method =} \StringTok{"silhouette"}\NormalTok{,       }\CommentTok{\# Criterio de las siluetas}
             \AttributeTok{k.max =} \DecValTok{10}\NormalTok{,                 }\CommentTok{\# Máximo número de clusters a probar}
             \AttributeTok{linecolor =} \StringTok{"blue"}\NormalTok{)         }\CommentTok{\# Color de la línea}

\FunctionTok{library}\NormalTok{(factoextra)}
\FunctionTok{library}\NormalTok{(vegan)}

\CommentTok{\# Calcular la disimilitud de Bray{-}Curtis y luego aplicar la raíz cuadrada}
\NormalTok{dissimilarity\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{vegdist}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(selected\_data)), }\AttributeTok{method =} \StringTok{"bray"}\NormalTok{)}

\CommentTok{\# Realizar el análisis jerárquico}
\NormalTok{hc }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(dissimilarity\_matrix, }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}

\CommentTok{\# Determinar el número óptimo de clusters usando el criterio WSS (Suma de cuadrados dentro de los grupos)}
\FunctionTok{fviz\_nbclust}\NormalTok{(selected\_data, }
             \AttributeTok{FUNcluster =}\NormalTok{ hcut,           }\CommentTok{\# Usamos hcut para cortar el dendrograma}
             \AttributeTok{method =} \StringTok{"wss"}\NormalTok{,              }\CommentTok{\# Criterio de la suma de cuadrados dentro de los grupos}
             \AttributeTok{k.max =} \DecValTok{10}\NormalTok{,                 }\CommentTok{\# Máximo número de clusters a probar}
             \AttributeTok{linecolor =} \StringTok{"blue"}\NormalTok{)         }\CommentTok{\# Color de la línea}

\CommentTok{\# Determinar el número óptimo de clusters usando el criterio de las siluetas con PAM}
\FunctionTok{fviz\_nbclust}\NormalTok{(selected\_data, }
             \AttributeTok{FUNcluster =}\NormalTok{ pam,            }\CommentTok{\# Usamos PAM para el clustering}
             \AttributeTok{method =} \StringTok{"silhouette"}\NormalTok{,       }\CommentTok{\# Criterio de las siluetas}
             \AttributeTok{diss =}\NormalTok{ dissimilarity\_matrix, }\CommentTok{\# Usar la matriz de disimilitud}
             \AttributeTok{k.max =} \DecValTok{10}\NormalTok{,                 }\CommentTok{\# Máximo número de clusters a probar}
             \AttributeTok{linecolor =} \StringTok{"blue"}\NormalTok{)         }\CommentTok{\# Color de la línea}
\end{Highlighting}
\end{Shaded}

\hypertarget{g-3}{%
\paragraph{G)}\label{g-3}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Determinar el número óptimo de clusters usando el criterio de las siluetas con PAM}
\FunctionTok{fviz\_nbclust}\NormalTok{(selected\_data, }
             \AttributeTok{FUNcluster =}\NormalTok{ pam,            }\CommentTok{\# Usamos PAM para el clustering}
             \AttributeTok{method =} \StringTok{"silhouette"}\NormalTok{,       }\CommentTok{\# Criterio de las siluetas}
             \AttributeTok{diss =}\NormalTok{ dissimilarity\_matrix, }\CommentTok{\# Usar la matriz de disimilitud}
             \AttributeTok{k.max =} \DecValTok{10}\NormalTok{,                 }\CommentTok{\# Máximo número de clusters a probar}
             \AttributeTok{linecolor =} \StringTok{"blue"}\NormalTok{)         }\CommentTok{\# Color de la línea}
\end{Highlighting}
\end{Shaded}

\hypertarget{h-3}{%
\paragraph{H)}\label{h-3}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Realizar el análisis jerárquico (ward.D2)}
\NormalTok{dendrogram }\OtherTok{\textless{}{-}} \FunctionTok{hclust}\NormalTok{(dissimilarity\_matrix, }\AttributeTok{method =} \StringTok{"ward.D2"}\NormalTok{)}

\CommentTok{\# Dibujar el dendrograma con la partición de 6 grupos}
\FunctionTok{plot}\NormalTok{(dendrogram, }\AttributeTok{main =} \StringTok{"Dendrograma con 6 clusters"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Muestras"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Distancia"}\NormalTok{)}
\FunctionTok{rect.hclust}\NormalTok{(dendrogram, }\AttributeTok{k =} \DecValTok{6}\NormalTok{, }\AttributeTok{border =} \StringTok{"red"}\NormalTok{)  }\CommentTok{\# Añadir rectángulos para marcar los 6 clusters}

\FunctionTok{library}\NormalTok{(vegan)}

\CommentTok{\# Asegúrate de que los datos sean numéricos}
\NormalTok{species\_frequency\_table }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{sapply}\NormalTok{(selected\_data, as.numeric))}

\CommentTok{\# Dividir las muestras en 6 clusters}
\NormalTok{cluster\_assignment }\OtherTok{\textless{}{-}} \FunctionTok{cutree}\NormalTok{(dendrogram, }\AttributeTok{k =} \DecValTok{6}\NormalTok{)}

\CommentTok{\# Calcular las medianas por especie en cada cluster}
\CommentTok{\# Usar tapply para calcular la mediana por cada especie (columna) en cada cluster}
\NormalTok{medians\_by\_cluster }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(species\_frequency\_table, }\DecValTok{2}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{tapply}\NormalTok{(x, cluster\_assignment, median))}

\CommentTok{\# Crear una tabla de medianas}
\NormalTok{medians\_table }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(medians\_by\_cluster)}

\CommentTok{\# Imprimir la tabla de medianas}
\CommentTok{\#print(medians\_table)}


\CommentTok{\# Filtrar especies con mediana \textless{}= 4 en todos los clusters}
\NormalTok{medians\_filtered }\OtherTok{\textless{}{-}}\NormalTok{ medians\_table[, }\FunctionTok{colSums}\NormalTok{(medians\_table }\SpecialCharTok{\textless{}=} \DecValTok{4}\NormalTok{) }\SpecialCharTok{!=} \FunctionTok{nrow}\NormalTok{(medians\_table)]}

\FunctionTok{print}\NormalTok{(medians\_filtered)}

\CommentTok{\# Realizar el análisis de correspondencias (CA) con la tabla filtrada}
\NormalTok{ca\_result }\OtherTok{\textless{}{-}} \FunctionTok{cca}\NormalTok{(medians\_filtered)}

\CommentTok{\# Mostrar los resultados del análisis}
\FunctionTok{summary}\NormalTok{(ca\_result)}

\FunctionTok{ordiplot}\NormalTok{(ca\_result, }\AttributeTok{type =} \StringTok{"text"}\NormalTok{, }\AttributeTok{main =} \StringTok{"Gráfico Asimétrico del Análisis de Correspondencia"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}


\end{document}
